# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nikolay Lositskiy
email: niklos2506@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: LositskiyNick
github_username:  nikolaylositskiy
facebook_username: nikolay.lositskiy
upwork_username: ~010ec093cc64583f0b
linkedin_username: lositskiy-nikolay-899548a3

# Address information
address_city: Kharkiv
address_state: Ukraine


# Build settings
markdown: kramdown
